'use strict';

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  EXAM_CLOSED: 'EXAM_CLOSED',
  ATTEMPT_SUBMITTED: 'ATTEMPT_SUBMITTED',
  OLD_ANSWER_VERSION: 'OLD_ANSWER_VERSION',
  DATABASE_ERROR: 'DATABASE_ERROR',
  QUESTION_IMMUTABLE: 'QUESTION_IMMUTABLE',
  EXAM_NOT_EDITABLE: 'EXAM_NOT_EDITABLE',
  EXAM_HAS_ATTEMPTS: 'EXAM_HAS_ATTEMPTS',
  NOT_CLASS_MEMBER: 'NOT_CLASS_MEMBER',
  EXAM_NOT_PUBLISHED: 'EXAM_NOT_PUBLISHED',
  EXAM_TIME_NOT_OPEN: 'EXAM_TIME_NOT_OPEN',
  ATTEMPT_LIMIT_REACHED: 'ATTEMPT_LIMIT_REACHED',
  ATTEMPT_NOT_IN_PROGRESS: 'ATTEMPT_NOT_IN_PROGRESS',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  RESULTS_NOT_PUBLISHED: 'RESULTS_NOT_PUBLISHED',
  INCIDENT_ALREADY_REVIEWED: 'INCIDENT_ALREADY_REVIEWED',
  INCIDENT_DUPLICATE_APPROVAL: 'INCIDENT_DUPLICATE_APPROVAL',
};

const STATUS_BY_CODE = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  EXAM_CLOSED: 403,
  ATTEMPT_SUBMITTED: 409,
  OLD_ANSWER_VERSION: 409,
  DATABASE_ERROR: 500,
  QUESTION_IMMUTABLE: 422,
  EXAM_NOT_EDITABLE: 422,
  EXAM_HAS_ATTEMPTS: 409,
  NOT_CLASS_MEMBER: 403,
  EXAM_NOT_PUBLISHED: 422,
  EXAM_TIME_NOT_OPEN: 422,
  ATTEMPT_LIMIT_REACHED: 422,
  ATTEMPT_NOT_IN_PROGRESS: 422,
  DEADLINE_PASSED: 422,
  RESULTS_NOT_PUBLISHED: 422,
  INCIDENT_ALREADY_REVIEWED: 409,
  INCIDENT_DUPLICATE_APPROVAL: 409,
};

class AppError extends Error {
  constructor(message, code = 'VALIDATION_ERROR', status, details) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.status = status || STATUS_BY_CODE[code] || 500;
    this.details = details;
    this.isOperational = true;
  }
}

module.exports = {
  AppError,
  ERROR_CODES,
  STATUS_BY_CODE,
};
